In [ ]:
beras = 11400
minyak = 12700	
ayam = 3400	
telur =	21800	
popok =	27000	
sabun_cuci = 1800	
buah_anggur =	3800	
roti_tawar = 8500	
tissu = 6400	
mie_instan = 2200
diskon1 = 90
diskon2 = 85
diskon3 = 80
diskon4 = 75


print("belanjaan tia")
beras_tia = 4
ayam_tia = 2
telur_tia = 3
sabun_cuci_tia = 5
buah_anggur_tia = 4
roti_tawar_tia = 2
mie_instan_tia = 12
jb_tia = (beras_tia * beras) + (ayam_tia * (ayam * 10)) + (telur_tia * telur) + (sabun_cuci_tia * sabun_cuci) + (buah_anggur_tia * buah_anggur ) + (roti_tawar_tia * roti_tawar) + (mie_instan_tia * mie_instan)
print("jumlah belanjaan tia " + str(jb_tia) + " RP");
jb_diskon_tia = (jb_tia / 100) * diskon2
print("maka jumlah belanjaan tia setelah mendapatkan diakon adalah " + str(jb_diskon_tia) + " RP")

print("belanjaan hana")
minyak_hana = 2
ayam_hana = 5
telur_hana = 1.5
sabun_cuci_hana = 3
buah_anggur_hana = 8
roti_tawar_hana = 3
tisu_hana = 2
mie_instan_hana = 20
jb_hana = (minyak_hana * minyak) + (ayam_hana * ayam) + (telur_hana * telur) + (sabun_cuci_hana * sabun_cuci) + (buah_anggur_hana * buah_anggur ) + (roti_tawar_hana * roti_tawar) + (tisu_hana * tissu) + (mie_instan_hana * mie_instan)
print("jumlah belanjaan hana " + str(jb_hana) + " RP")
jb_diskon_hana = (jb_hana / 100) * diskon1
print("maka jumlah belanjaan hana setelah mendapatkan diakon adalah " + str(jb_diskon_hana) + " RP")

print("belanjaan widia")
beras_widia = 1
minyak_widia = 1
telur_widia = 1
buah_anggur_widia = 5
tisu_widia = 3
mie_instan_widia = 16
jb_widia = (beras_widia * beras) + (minyak_widia * minyak) + (telur_widia * telur) + (buah_anggur_widia * buah_anggur ) + (tisu_widia * tissu) + (mie_instan_widia * mie_instan)
print("jumlah belanjaan widia " + str(jb_widia) + " RP")

print("belanjaan romi")
minyak_romi = 3
telur_romi = 2
popok_romi = 4
sabun_cuci_romi = 8
mie_instan_romi = 8
jb_romi = (minyak_romi * minyak) + (telur_romi * telur) + (popok_romi * popok) + (sabun_cuci_romi * sabun_cuci) + (mie_instan_romi * mie_instan)
print("jumlah belanjaan romi " + str(jb_romi) + " RP")
jb_diskon_romi = (jb_romi / 100) * diskon2
print("maka jumlah belanjaan romi setelah mendapatkan diakon adalah " + str(jb_diskon_romi) + " RP")


print("belanjaan samsul")
ayam_samsul = 3
telur_samsul = 4
popok_samsul = 2
buah_anggur_samsul = 7
tissu_samsul = 5
mie_instan_samsul = 10
jb_samsul = (ayam_samsul * (ayam * 10 )) + (telur_samsul * telur) + (popok_samsul * popok) + (buah_anggur_samsul * buah_anggur) + (tissu_samsul * tissu) + (mie_instan_samsul * mie_instan)
print("jumlah belanjaan samsul " + str(jb_samsul) + " RP")
jb_diskon_samsul = (jb_samsul / 100) * diskon4
print("maka jumlah belanjaan samsul setelah mendapatkan diakon adalah " + str(jb_diskon_samsul) + " RP")


print("belanjaan dimas")
ayam_dimas = 5
popok_dimas = 5
sabun_cuci_dimas = 4
buah_anggur_dimas = 3
roti_tawar_dimas = 5
mie_instan_dimas = 6
jb_dimas = (ayam_dimas * (ayam * 10)) + (popok_dimas * popok) + (sabun_cuci_dimas * sabun_cuci) + (buah_anggur_dimas * buah_anggur) + (roti_tawar_dimas * roti_tawar)  + (mie_instan_dimas * mie_instan)
print("jumlah belanjaan dimas " + str(jb_dimas) + " RP")
jb_diskon_dimas = (jb_dimas / 100) * diskon4
print("maka jumlah belanjaan dimas setelah mendapatkan diakon adalah " + str(jb_diskon_dimas) + " RP")
print()
max = [284475]
print("maka julah belanjaanpaling besar setelah mendaoatkan diskon adalah DIMAS RP. : " +str(max))
print()
persen = [173800]
print("maka belanjaan yang mendapatkan diskon 10% adalah HANA RP. : " +str(persen))

belanjaan tia
jumlah belanjaan tia 246600 RP
maka jumlah belanjaan tia setelah mendapatkan diakon adalah 209610.0 RP
belanjaan hana
jumlah belanjaan hana 193200.0 RP
maka jumlah belanjaan hana setelah mendapatkan diakon adalah 173880.0 RP
belanjaan widia
jumlah belanjaan widia 119300 RP
belanjaan romi
jumlah belanjaan romi 221700 RP
maka jumlah belanjaan romi setelah mendapatkan diakon adalah 188445.0 RP
belanjaan samsul
jumlah belanjaan samsul 323800 RP
maka jumlah belanjaan samsul setelah mendapatkan diakon adalah 242850.0 RP
belanjaan dimas
jumlah belanjaan dimas 379300 RP
maka jumlah belanjaan dimas setelah mendapatkan diakon adalah 284475.0 RP

maka julah belanjaanpaling besar setelah mendaoatkan diskon adalah DIMAS RP. : [284475]

maka belanjaan yang mendapatkan diskon 10% adalah HANA RP. : [173800]